from django.db import models

class TeamRegistration(models.Model):
    id = models.BigAutoField(primary_key=True)
    team_name = models.CharField(unique=True, max_length=255)
    team_size = models.IntegerField()
    theme = models.CharField(max_length=255)
    transaction_id = models.CharField(unique=True, max_length=100)
    payment_screenshot = models.CharField(max_length=500, blank=True, null=True)
    
    selection_status = models.CharField(max_length=20, default='pending')
    
    member1_name = models.CharField(max_length=255)
    member1_email = models.CharField(max_length=254)
    member1_phone = models.CharField(max_length=20)
    member1_roll = models.CharField(max_length=50)
    member1_gender = models.CharField(max_length=20)
    member1_college_name = models.CharField(max_length=255)
    member1_college_code = models.CharField(max_length=50)
    member1_course_name = models.CharField(max_length=255)
    member1_year = models.CharField(max_length=50)
    member1_tshirt_size = models.CharField(max_length=10)
    member1_food_preference = models.CharField(max_length=50)
    is_leader1 = models.BooleanField()
    
    member2_name = models.CharField(max_length=255)
    member2_email = models.CharField(max_length=254)
    member2_phone = models.CharField(max_length=20)
    member2_roll = models.CharField(max_length=50)
    member2_gender = models.CharField(max_length=20)
    member2_college_name = models.CharField(max_length=255)
    member2_college_code = models.CharField(max_length=50)
    member2_course_name = models.CharField(max_length=255)
    member2_year = models.CharField(max_length=50)
    member2_tshirt_size = models.CharField(max_length=10)
    member2_food_preference = models.CharField(max_length=50)
    is_leader2 = models.BooleanField()
    
    member3_name = models.CharField(max_length=255)
    member3_email = models.CharField(max_length=254)
    member3_phone = models.CharField(max_length=20)
    member3_roll = models.CharField(max_length=50)
    member3_gender = models.CharField(max_length=20)
    member3_college_name = models.CharField(max_length=255)
    member3_college_code = models.CharField(max_length=50)
    member3_course_name = models.CharField(max_length=255)
    member3_year = models.CharField(max_length=50)
    member3_tshirt_size = models.CharField(max_length=10)
    member3_food_preference = models.CharField(max_length=50)
    is_leader3 = models.BooleanField()
    
    member4_name = models.CharField(max_length=255)
    member4_email = models.CharField(max_length=254)
    member4_phone = models.CharField(max_length=20)
    member4_roll = models.CharField(max_length=50)
    member4_gender = models.CharField(max_length=20)
    member4_college_name = models.CharField(max_length=255)
    member4_college_code = models.CharField(max_length=50)
    member4_course_name = models.CharField(max_length=255)
    member4_year = models.CharField(max_length=50)
    member4_tshirt_size = models.CharField(max_length=10)
    member4_food_preference = models.CharField(max_length=50)
    is_leader4 = models.BooleanField()
    
    member5_name = models.CharField(max_length=255, blank=True, null=True)
    member5_email = models.CharField(max_length=254, blank=True, null=True)
    member5_phone = models.CharField(max_length=20, blank=True, null=True)
    member5_roll = models.CharField(max_length=50, blank=True, null=True)
    member5_gender = models.CharField(max_length=20, blank=True, null=True)
    member5_college_name = models.CharField(max_length=255, blank=True, null=True)
    member5_college_code = models.CharField(max_length=50, blank=True, null=True)
    member5_course_name = models.CharField(max_length=255, blank=True, null=True)
    member5_year = models.CharField(max_length=50, blank=True, null=True)
    member5_tshirt_size = models.CharField(max_length=10, blank=True, null=True)
    member5_food_preference = models.CharField(max_length=50, blank=True, null=True)
    is_leader5 = models.BooleanField(default=False)
    
    member6_name = models.CharField(max_length=255, blank=True, null=True)
    member6_email = models.CharField(max_length=254, blank=True, null=True)
    member6_phone = models.CharField(max_length=20, blank=True, null=True)
    member6_roll = models.CharField(max_length=50, blank=True, null=True)
    member6_gender = models.CharField(max_length=20, blank=True, null=True)
    member6_college_name = models.CharField(max_length=255, blank=True, null=True)
    member6_college_code = models.CharField(max_length=50, blank=True, null=True)
    member6_course_name = models.CharField(max_length=255, blank=True, null=True)
    member6_year = models.CharField(max_length=50, blank=True, null=True)
    member6_tshirt_size = models.CharField(max_length=10, blank=True, null=True)
    member6_food_preference = models.CharField(max_length=50, blank=True, null=True)
    is_leader6 = models.BooleanField(default=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        db_table = 'website_teamregistration'
